Repository petqua/backend, pull requests merged in 2024-02, with the labels that each got.

#34 feature: 봉달 목록내 상품 수정 api
  src/main/kotlin/com/petqua/application/cart/CartProductService.kt
  src/main/kotlin/com/petqua/application/cart/dto/CartProductDtos.kt
  src/main/kotlin/com/petqua/domain/cart/CartProduct.kt
  src/main/kotlin/com/petqua/domain/cart/CartProductQuantity.kt
  src/main/kotlin/com/petqua/exception/cart/CartProductExceptionType.kt
  src/main/kotlin/com/petqua/presentation/cart/CartProductController.kt
  src/main/kotlin/com/petqua/presentation/cart/dto/CartProductDtos.kt
  src/test/kotlin/com/petqua/application/cart/CartProductServiceTest.kt
  src/test/kotlin/com/petqua/domain/auth/FakeKakaoOauthApiClient.kt
  src/test/kotlin/com/petqua/domain/cart/CartProductTest.kt
  src/test/kotlin/com/petqua/presentation/cart/CartProductControllerSteps.kt
  src/test/kotlin/com/petqua/presentation/cart/CartProductControllerTest.kt
  src/test/kotlin/com/petqua/test/fixture/CartProductFixtures.kt
Labels: feat

#37 feature: 봉달 목록내 상품 제거 api
  src/main/kotlin/com/petqua/application/cart/CartProductService.kt
  src/main/kotlin/com/petqua/application/cart/dto/CartProductDtos.kt
  src/main/kotlin/com/petqua/domain/cart/CartProductRepository.kt
  src/main/kotlin/com/petqua/presentation/cart/CartProductController.kt
  src/test/kotlin/com/petqua/application/cart/CartProductServiceTest.kt
  src/test/kotlin/com/petqua/presentation/cart/CartProductControllerSteps.kt
  src/test/kotlin/com/petqua/presentation/cart/CartProductControllerTest.kt
Labels: feat

#38 feature: 봉달 목록 조회 api
  src/main/kotlin/com/petqua/application/cart/CartProductService.kt
  src/main/kotlin/com/petqua/application/cart/dto/CartProductDtos.kt
  src/main/kotlin/com/petqua/common/util/EntityManagerUtils.kt
  src/main/kotlin/com/petqua/domain/cart/CartProductCustomRepository.kt
  src/main/kotlin/com/petqua/domain/cart/CartProductCustomRepositoryImpl.kt
  src/main/kotlin/com/petqua/domain/cart/CartProductRepository.kt
  src/main/kotlin/com/petqua/domain/product/ProductCustomRepository.kt
  src/main/kotlin/com/petqua/domain/product/ProductCustomRepositoryImpl.kt
  src/main/kotlin/com/petqua/presentation/cart/CartProductController.kt
  src/test/kotlin/com/petqua/application/cart/CartProductServiceTest.kt
  src/test/kotlin/com/petqua/domain/product/ProductCustomRepositoryImplTest.kt
  src/test/kotlin/com/petqua/presentation/cart/CartProductControllerSteps.kt
  src/test/kotlin/com/petqua/presentation/cart/CartProductControllerTest.kt
  src/test/kotlin/com/petqua/presentation/product/ProductControllerTest.kt
  src/test/kotlin/com/petqua/test/fixture/CartProductFixtures.kt
  src/test/kotlin/com/petqua/test/fixture/MemberFixtures.kt
Labels: feat

#42 feature: 상품 검색 API(with 자동완성)
  src/main/kotlin/com/petqua/application/product/ProductService.kt
  src/main/kotlin/com/petqua/application/product/dto/ProductDtos.kt
  src/main/kotlin/com/petqua/common/util/EntityManagerUtils.kt
  src/main/kotlin/com/petqua/domain/keyword/ProductKeyword.kt
  src/main/kotlin/com/petqua/domain/keyword/ProductKeywordCustomRepository.kt
  src/main/kotlin/com/petqua/domain/keyword/ProductKeywordCustomRepositoryImpl.kt
  src/main/kotlin/com/petqua/domain/keyword/ProductKeywordRepository.kt
  src/main/kotlin/com/petqua/domain/product/ProductCustomRepository.kt
  src/main/kotlin/com/petqua/domain/product/ProductCustomRepositoryImpl.kt
  src/main/kotlin/com/petqua/domain/product/ProductDynamicJpqlGenerator.kt
  src/main/kotlin/com/petqua/domain/product/dto/ProductDtos.kt
  src/main/kotlin/com/petqua/exception/product/ProductExceptionType.kt
  src/main/kotlin/com/petqua/presentation/product/ProductController.kt
  src/main/kotlin/com/petqua/presentation/product/dto/ProductDtos.kt
  src/test/kotlin/com/petqua/application/product/ProductServiceTest.kt
  src/test/kotlin/com/petqua/domain/product/ProductCustomRepositoryImplTest.kt
  src/test/kotlin/com/petqua/domain/product/ProductKeywordCustomRepositoryImplTest.kt
  src/test/kotlin/com/petqua/domain/product/ProductKeywordTest.kt
  src/test/kotlin/com/petqua/presentation/product/ProductControllerSteps.kt
  src/test/kotlin/com/petqua/presentation/product/ProductControllerTest.kt
  src/test/kotlin/com/petqua/test/fixture/ProductFixtures.kt
Labels: feat

#46 refactor: lastViewedId default 값 설정
  src/main/kotlin/com/petqua/domain/product/dto/ProductDtos.kt
Labels: refactor

#50 feature: Swagger API 명세 추가
  build.gradle.kts
  src/main/kotlin/com/petqua/application/announcement/AnnouncementDtos.kt
  src/main/kotlin/com/petqua/application/banner/dto/BannerDtos.kt
  src/main/kotlin/com/petqua/application/cart/dto/CartProductDtos.kt
  src/main/kotlin/com/petqua/application/product/dto/ProductDtos.kt
  src/main/kotlin/com/petqua/common/config/CorsConfig.kt
  src/main/kotlin/com/petqua/common/config/SwaggerConfig.kt
  src/main/kotlin/com/petqua/domain/auth/LoginMember.kt
  src/main/kotlin/com/petqua/domain/product/dto/ProductDtos.kt
  src/main/kotlin/com/petqua/presentation/announcement/AnnouncementController.kt
  src/main/kotlin/com/petqua/presentation/auth/AuthController.kt
  src/main/kotlin/com/petqua/presentation/banner/BannerController.kt
  src/main/kotlin/com/petqua/presentation/cart/CartProductController.kt
  src/main/kotlin/com/petqua/presentation/cart/dto/CartProductDtos.kt
  src/main/kotlin/com/petqua/presentation/product/ProductController.kt
  src/main/kotlin/com/petqua/presentation/product/WishProductController.kt
  src/main/kotlin/com/petqua/presentation/product/WishProductDtos.kt
  src/main/kotlin/com/petqua/presentation/product/dto/ProductDtos.kt
Labels: feat

#54 refactor: 변수명 변경
  src/main/kotlin/com/petqua/presentation/product/WishProductDtos.kt
  src/test/kotlin/com/petqua/application/product/WishProductServiceTest.kt
  src/test/kotlin/com/petqua/presentation/product/WishProductControllerTest.kt
Labels: refactor

#56 refactor: CORS 설정 변경
  src/main/kotlin/com/petqua/common/config/CorsConfig.kt
  src/test/kotlin/com/petqua/common/config/CorsConfigTest.kt
Labels: refactor

#59 refactor: Auth Swagger 명세 다시 추가
  src/main/kotlin/com/petqua/presentation/auth/AuthController.kt
  src/main/kotlin/com/petqua/presentation/auth/AuthDtos.kt
Labels: refactor

#65 refactor: auth 응답 변경
  src/main/kotlin/com/petqua/presentation/auth/AuthController.kt
  src/main/kotlin/com/petqua/presentation/auth/AuthDtos.kt
  src/test/kotlin/com/petqua/presentation/auth/AuthControllerTest.kt
  src/test/kotlin/com/petqua/test/ApiTestConfig.kt
Labels: refactor

#64 feature: 상품 후기 조회 api
  src/main/kotlin/com/petqua/application/product/WishProductService.kt
  src/main/kotlin/com/petqua/application/product/dto/ProductDtos.kt
  src/main/kotlin/com/petqua/application/product/dto/ProductReviewDtos.kt
  src/main/kotlin/com/petqua/application/product/dto/WishProductDtos.kt
  src/main/kotlin/com/petqua/application/product/review/ProductReviewService.kt
  src/main/kotlin/com/petqua/common/config/DataInitializer.kt
  src/main/kotlin/com/petqua/common/domain/dto/CursorBasedPaging.kt
  src/main/kotlin/com/petqua/domain/member/Member.kt
  src/main/kotlin/com/petqua/domain/product/ProductCustomRepository.kt
  src/main/kotlin/com/petqua/domain/product/ProductCustomRepositoryImpl.kt
  src/main/kotlin/com/petqua/domain/product/WishProductCustomRepository.kt
  src/main/kotlin/com/petqua/domain/product/WishProductCustomRepositoryImpl.kt
  src/main/kotlin/com/petqua/domain/product/dto/ProductDtos.kt
  src/main/kotlin/com/petqua/domain/product/dto/ProductReviewDtos.kt
  src/main/kotlin/com/petqua/domain/product/review/ProductReview.kt
  src/main/kotlin/com/petqua/domain/product/review/ProductReviewCustomRepository.kt
  src/main/kotlin/com/petqua/domain/product/review/ProductReviewCustomRepositoryImpl.kt
  src/main/kotlin/com/petqua/domain/product/review/ProductReviewDynamicJpqlGenerator.kt
  src/main/kotlin/com/petqua/domain/product/review/ProductReviewImage.kt
  src/main/kotlin/com/petqua/domain/product/review/ProductReviewImageRepository.kt
  src/main/kotlin/com/petqua/domain/product/review/ProductReviewRepository.kt
  src/main/kotlin/com/petqua/domain/product/review/ProductReviewSorter.kt
  src/main/kotlin/com/petqua/presentation/product/ProductReviewController.kt
  src/main/kotlin/com/petqua/presentation/product/WishProductController.kt
  src/main/kotlin/com/petqua/presentation/product/dto/ProductDtos.kt
  src/main/kotlin/com/petqua/presentation/product/dto/ProductReviewDtos.kt
  src/main/kotlin/com/petqua/presentation/product/dto/WishProductDtos.kt
  src/test/kotlin/com/petqua/application/product/WishProductServiceTest.kt
  src/test/kotlin/com/petqua/application/product/review/ProductReviewServiceTest.kt
  src/test/kotlin/com/petqua/domain/product/ProductCustomRepositoryImplTest.kt
  src/test/kotlin/com/petqua/domain/product/review/ProductReviewCustomRepositoryImplTest.kt
  src/test/kotlin/com/petqua/presentation/cart/CartProductControllerSteps.kt
  src/test/kotlin/com/petqua/presentation/product/ProductControllerSteps.kt
  src/test/kotlin/com/petqua/presentation/product/ProductReviewControllerSteps.kt
  src/test/kotlin/com/petqua/presentation/product/ProductReviewControllerTest.kt
  src/test/kotlin/com/petqua/presentation/product/WishProductControllerTest.kt
  src/test/kotlin/com/petqua/test/fixture/MemberFixtures.kt
  src/test/kotlin/com/petqua/test/fixture/ProductReviewFixtures.kt
Labels: feature

#69 feature: 카테고리 상품 조회 api
  src/main/kotlin/com/petqua/application/cart/CartProductService.kt
  src/main/kotlin/com/petqua/application/cart/dto/CartProductDtos.kt
  src/main/kotlin/com/petqua/application/product/ProductService.kt
  src/main/kotlin/com/petqua/application/product/category/CategoryDto.kt
  src/main/kotlin/com/petqua/application/product/category/CategoryService.kt
  src/main/kotlin/com/petqua/application/product/dto/ProductDtos.kt
  src/main/kotlin/com/petqua/common/config/DataInitializer.kt
  src/main/kotlin/com/petqua/domain/cart/CartProduct.kt
  src/main/kotlin/com/petqua/domain/cart/CartProductRepository.kt
  src/main/kotlin/com/petqua/domain/delivery/DeliveryMethod.kt
  src/main/kotlin/com/petqua/domain/product/Product.kt
  src/main/kotlin/com/petqua/domain/product/ProductCustomRepository.kt
  src/main/kotlin/com/petqua/domain/product/ProductCustomRepositoryImpl.kt
  src/main/kotlin/com/petqua/domain/product/ProductDynamicJpqlGenerator.kt
  src/main/kotlin/com/petqua/domain/product/category/Category.kt
  src/main/kotlin/com/petqua/domain/product/category/CategoryCustomRepository.kt
  src/main/kotlin/com/petqua/domain/product/category/CategoryCustomRepositoryImpl.kt
  src/main/kotlin/com/petqua/domain/product/category/CategoryDto.kt
  src/main/kotlin/com/petqua/domain/product/category/CategoryRepository.kt
  src/main/kotlin/com/petqua/domain/product/category/Family.kt
  src/main/kotlin/com/petqua/domain/product/category/Species.kt
  src/main/kotlin/com/petqua/domain/product/dto/ProductDtos.kt
  src/main/kotlin/com/petqua/presentation/cart/dto/CartProductDtos.kt
  src/main/kotlin/com/petqua/presentation/product/category/CategoryController.kt
  src/main/kotlin/com/petqua/presentation/product/category/CategoryDto.kt
  src/main/kotlin/com/petqua/presentation/product/dto/ProductDtos.kt
  src/main/kotlin/com/petqua/presentation/product/dto/WishProductDtos.kt
  src/test/kotlin/com/petqua/application/cart/CartProductServiceTest.kt
  src/test/kotlin/com/petqua/application/product/category/CategoryServiceTest.kt
  src/test/kotlin/com/petqua/domain/cart/CartProductTest.kt
  src/test/kotlin/com/petqua/domain/product/ProductCustomRepositoryImplTest.kt
  src/test/kotlin/com/petqua/domain/product/category/CategoryCustomRepositoryImplTest.kt
  src/test/kotlin/com/petqua/presentation/product/ProductControllerSteps.kt
  src/test/kotlin/com/petqua/presentation/product/ProductControllerTest.kt
  src/test/kotlin/com/petqua/presentation/product/category/CategoryControllerSteps.kt
  src/test/kotlin/com/petqua/presentation/product/category/CategoryControllerTest.kt
  src/test/kotlin/com/petqua/test/fixture/CartProductFixtures.kt
  src/test/kotlin/com/petqua/test/fixture/CategoryFixtures.kt
  src/test/kotlin/com/petqua/test/fixture/ProductFixtures.kt
Labels: feature

#76 feature: 상품 상세 조회 api
  src/main/kotlin/com/petqua/application/product/ProductService.kt
  src/main/kotlin/com/petqua/application/product/dto/ProductDtos.kt
  src/main/kotlin/com/petqua/common/config/DataInitializer.kt
  src/main/kotlin/com/petqua/common/config/WebConfig.kt
  src/main/kotlin/com/petqua/common/util/EntityManagerUtils.kt
  src/main/kotlin/com/petqua/domain/auth/LoginMemberOrGuest.kt
  src/main/kotlin/com/petqua/domain/product/ProductCustomRepository.kt
  src/main/kotlin/com/petqua/domain/product/ProductCustomRepositoryImpl.kt
  src/main/kotlin/com/petqua/domain/product/WishProduct.kt
  src/main/kotlin/com/petqua/domain/product/WishProductRepository.kt
  src/main/kotlin/com/petqua/domain/product/detail/DifficultyLevel.kt
  src/main/kotlin/com/petqua/domain/product/detail/OptimalTankSize.kt
  src/main/kotlin/com/petqua/domain/product/detail/OptimalTemperature.kt
  src/main/kotlin/com/petqua/domain/product/detail/ProductImage.kt
  src/main/kotlin/com/petqua/domain/product/detail/ProductImageRepository.kt
  src/main/kotlin/com/petqua/domain/product/detail/ProductInfo.kt
  src/main/kotlin/com/petqua/domain/product/detail/ProductInfoRepository.kt
  src/main/kotlin/com/petqua/domain/product/detail/Temperament.kt
  src/main/kotlin/com/petqua/domain/product/dto/ProductDtos.kt
  src/main/kotlin/com/petqua/domain/product/option/ProductOption.kt
  src/main/kotlin/com/petqua/domain/product/option/ProductOptionRepository.kt
  src/main/kotlin/com/petqua/domain/product/option/Sex.kt
  src/main/kotlin/com/petqua/presentation/auth/AuthExtractor.kt
  src/main/kotlin/com/petqua/presentation/auth/OptionalLoginArgumentResolver.kt
  src/main/kotlin/com/petqua/presentation/product/ProductController.kt
  src/main/kotlin/com/petqua/presentation/product/dto/ProductDtos.kt
  src/test/kotlin/com/petqua/application/product/ProductServiceTest.kt
  src/test/kotlin/com/petqua/application/product/WishProductServiceTest.kt
  src/test/kotlin/com/petqua/domain/product/ProductCustomRepositoryImplTest.kt
  src/test/kotlin/com/petqua/domain/product/WishProductRepositoryTest.kt
  src/test/kotlin/com/petqua/presentation/product/ProductControllerSteps.kt
  src/test/kotlin/com/petqua/presentation/product/ProductControllerTest.kt
  src/test/kotlin/com/petqua/test/fixture/ProductFixtures.kt
  src/test/kotlin/com/petqua/test/fixture/WishProductFixtures.kt
Labels: feature

#81 refactor: 카테고리 조회 상품 상세 조회 api swagger 반영
  src/main/kotlin/com/petqua/application/product/category/CategoryDto.kt
  src/main/kotlin/com/petqua/application/product/category/CategoryService.kt
  src/main/kotlin/com/petqua/common/config/DataInitializer.kt
  src/main/kotlin/com/petqua/domain/auth/LoginMemberOrGuest.kt
  src/main/kotlin/com/petqua/presentation/product/ProductController.kt
  src/main/kotlin/com/petqua/presentation/product/category/CategoryController.kt
  src/main/kotlin/com/petqua/presentation/product/category/CategoryDto.kt
  src/main/kotlin/com/petqua/presentation/product/dto/ProductDtos.kt
  src/test/kotlin/com/petqua/application/product/category/CategoryServiceTest.kt
  src/test/kotlin/com/petqua/presentation/product/ProductControllerSteps.kt
  src/test/kotlin/com/petqua/presentation/product/category/CategoryControllerSteps.kt
  src/test/kotlin/com/petqua/presentation/product/category/CategoryControllerTest.kt
  src/test/kotlin/com/petqua/test/TestUtil.kt
Labels: refactor

#66 feature: 상품 후기 통계 조회 api
  src/main/kotlin/com/petqua/application/product/dto/ProductReviewDtos.kt
  src/main/kotlin/com/petqua/application/product/review/ProductReviewService.kt
  src/main/kotlin/com/petqua/domain/product/Product.kt
  src/main/kotlin/com/petqua/domain/product/dto/ProductReviewDtos.kt
  src/main/kotlin/com/petqua/domain/product/review/ProductReviewCustomRepository.kt
  src/main/kotlin/com/petqua/domain/product/review/ProductReviewCustomRepositoryImpl.kt
  src/main/kotlin/com/petqua/domain/product/review/ProductReviewStatistics.kt
  src/main/kotlin/com/petqua/presentation/product/ProductReviewController.kt
  src/test/kotlin/com/petqua/application/product/review/ProductReviewServiceTest.kt
  src/test/kotlin/com/petqua/domain/product/review/ProductReviewCustomRepositoryImplTest.kt
  src/test/kotlin/com/petqua/domain/product/review/ProductReviewStatisticsTest.kt
  src/test/kotlin/com/petqua/presentation/product/ProductReviewControllerSteps.kt
  src/test/kotlin/com/petqua/presentation/product/ProductReviewControllerTest.kt
Labels: feature

#86 feat: 회원/비회에 따른 상품 후기 조회시 추천 여부 포함하여 응답
  src/main/kotlin/com/petqua/application/product/dto/ProductReviewDtos.kt
  src/main/kotlin/com/petqua/application/product/review/ProductReviewService.kt
  src/main/kotlin/com/petqua/domain/product/review/ProductReviewRecommendationRepository.kt
  src/main/kotlin/com/petqua/presentation/product/ProductReviewController.kt
  src/main/kotlin/com/petqua/presentation/product/dto/ProductReviewDtos.kt
  src/test/kotlin/com/petqua/application/product/review/ProductReviewServiceTest.kt
Labels: refactor

#91 fix: 초기 데이터 리뷰 별점 수정
  src/main/kotlin/com/petqua/common/config/DataInitializer.kt
  src/main/kotlin/com/petqua/domain/product/dto/ProductReviewDtos.kt
  src/main/kotlin/com/petqua/domain/product/review/ProductReview.kt
  src/main/kotlin/com/petqua/domain/product/review/ProductReviewCustomRepositoryImpl.kt
  src/main/kotlin/com/petqua/domain/product/review/ProductReviewDynamicJpqlGenerator.kt
  src/main/kotlin/com/petqua/domain/product/review/ProductReviewScore.kt
  src/main/kotlin/com/petqua/exception/product/review/ProductReviewExceptionType.kt
  src/test/kotlin/com/petqua/domain/product/review/ProductReviewScoreTest.kt
  src/test/kotlin/com/petqua/test/fixture/ProductReviewFixtures.kt
Labels: fix

#99 refactor: 찜 목록 조회 response 수정
  src/main/kotlin/com/petqua/presentation/product/dto/WishProductDtos.kt
Labels: refactor

#92 refactor: 상품 상세 조회 api 응답 필드 수정
  src/main/kotlin/com/petqua/application/product/ProductService.kt
  src/main/kotlin/com/petqua/application/product/dto/ProductDtos.kt
  src/main/kotlin/com/petqua/common/config/DataInitializer.kt
  src/main/kotlin/com/petqua/domain/product/Product.kt
  src/main/kotlin/com/petqua/domain/product/ProductCustomRepository.kt
  src/main/kotlin/com/petqua/domain/product/ProductCustomRepositoryImpl.kt
  src/main/kotlin/com/petqua/domain/product/detail/description/ProductDescription.kt
  src/main/kotlin/com/petqua/domain/product/detail/description/ProductDescriptionContent.kt
  src/main/kotlin/com/petqua/domain/product/detail/description/ProductDescriptionRepository.kt
  src/main/kotlin/com/petqua/domain/product/detail/description/ProductDescriptionTitle.kt
  src/main/kotlin/com/petqua/domain/product/detail/image/ImageType.kt
  src/main/kotlin/com/petqua/domain/product/detail/image/ProductImage.kt
  src/main/kotlin/com/petqua/domain/product/detail/image/ProductImageRepository.kt
  src/main/kotlin/com/petqua/domain/product/detail/info/DifficultyLevel.kt
  src/main/kotlin/com/petqua/domain/product/detail/info/OptimalTankSize.kt
  src/main/kotlin/com/petqua/domain/product/detail/info/OptimalTemperature.kt
  src/main/kotlin/com/petqua/domain/product/detail/info/ProductInfo.kt
  src/main/kotlin/com/petqua/domain/product/detail/info/ProductInfoRepository.kt
  src/main/kotlin/com/petqua/domain/product/detail/info/Temperament.kt
  src/main/kotlin/com/petqua/domain/product/dto/ProductDtos.kt
  src/main/kotlin/com/petqua/domain/product/option/ProductOption.kt
  src/test/kotlin/com/petqua/application/product/ProductServiceTest.kt
  src/test/kotlin/com/petqua/domain/product/ProductCustomRepositoryImplTest.kt
  src/test/kotlin/com/petqua/presentation/product/ProductControllerTest.kt
  src/test/kotlin/com/petqua/test/fixture/ProductFixtures.kt
Labels: refactor

#101 feature: 주문결제 api
  src/main/kotlin/com/petqua/application/order/OrderService.kt
  src/main/kotlin/com/petqua/application/order/dto/OrderDtos.kt
  src/main/kotlin/com/petqua/application/product/dto/ProductDtos.kt
  src/main/kotlin/com/petqua/common/config/DataInitializer.kt
  src/main/kotlin/com/petqua/domain/order/Order.kt
  src/main/kotlin/com/petqua/domain/order/OrderName.kt
  src/main/kotlin/com/petqua/domain/order/OrderNumber.kt
  src/main/kotlin/com/petqua/domain/order/OrderPayment.kt
  src/main/kotlin/com/petqua/domain/order/OrderProduct.kt
  src/main/kotlin/com/petqua/domain/order/OrderRepository.kt
  src/main/kotlin/com/petqua/domain/order/OrderShippingAddress.kt
  src/main/kotlin/com/petqua/domain/order/OrderShippingAddressInfo.kt
  src/main/kotlin/com/petqua/domain/order/OrderStatus.kt
  src/main/kotlin/com/petqua/domain/order/ShippingNumber.kt
  src/main/kotlin/com/petqua/domain/payment/tosspayment/TossPayment.kt
  src/main/kotlin/com/petqua/domain/product/Product.kt
  src/main/kotlin/com/petqua/domain/product/ProductCustomRepositoryImpl.kt
  src/main/kotlin/com/petqua/domain/product/ProductDynamicJpqlGenerator.kt
  src/main/kotlin/com/petqua/domain/product/ProductRepository.kt
  src/main/kotlin/com/petqua/domain/product/dto/ProductDtos.kt
  src/main/kotlin/com/petqua/domain/product/option/ProductOption.kt
  src/main/kotlin/com/petqua/domain/product/option/ProductOptionRepository.kt
  src/main/kotlin/com/petqua/domain/product/option/Sex.kt
  src/main/kotlin/com/petqua/domain/store/StoreRepository.kt
  src/main/kotlin/com/petqua/exception/order/OrderException.kt
  src/main/kotlin/com/petqua/exception/order/OrderExceptionType.kt
  src/main/kotlin/com/petqua/exception/order/ShippingAddressExceptionType.kt
  src/main/kotlin/com/petqua/exception/product/ProductExceptionType.kt
  src/main/kotlin/com/petqua/presentation/order/OrderController.kt
  src/main/kotlin/com/petqua/presentation/order/dto/OrderDtos.kt
  src/test/kotlin/com/petqua/application/order/OrderServiceTest.kt
  src/test/kotlin/com/petqua/application/product/ProductServiceTest.kt
  src/test/kotlin/com/petqua/application/product/category/CategoryServiceTest.kt
  src/test/kotlin/com/petqua/domain/product/ProductCustomRepositoryImplTest.kt
  src/test/kotlin/com/petqua/domain/product/ProductTest.kt
  src/test/kotlin/com/petqua/domain/product/category/CategoryCustomRepositoryImplTest.kt
  src/test/kotlin/com/petqua/presentation/product/ProductControllerTest.kt
  src/test/kotlin/com/petqua/presentation/product/category/CategoryControllerTest.kt
  src/test/kotlin/com/petqua/test/fixture/OrderFixture.kt
  src/test/kotlin/com/petqua/test/fixture/ProductFixtures.kt
Labels: feature

#104 fix: 상품 옵션 더미 데이터 추가 로직 변경
  src/main/kotlin/com/petqua/common/config/DataInitializer.kt
  src/main/kotlin/com/petqua/presentation/order/OrderController.kt
  src/test/kotlin/com/petqua/domain/product/ProductTest.kt
Labels: fix

#107 refactor: 콘솔 로거 프로퍼티 변경
  src/main/resources/logback-spring.xml
Labels: refactor

#96 feature: 회원 탈퇴 api
  build.gradle.kts
  src/main/kotlin/com/petqua/application/auth/AuthDtos.kt
  src/main/kotlin/com/petqua/application/auth/AuthFacadeService.kt
  src/main/kotlin/com/petqua/application/auth/AuthService.kt
  src/main/kotlin/com/petqua/application/auth/OauthService.kt
  src/main/kotlin/com/petqua/application/cart/CartProductService.kt
  src/main/kotlin/com/petqua/application/order/OrderService.kt
  src/main/kotlin/com/petqua/application/order/ShippingAddressService.kt
  src/main/kotlin/com/petqua/application/product/WishProductService.kt
  src/main/kotlin/com/petqua/application/product/review/ProductReviewService.kt
  src/main/kotlin/com/petqua/common/config/DataInitializer.kt
  src/main/kotlin/com/petqua/common/domain/Repository.kt
  src/main/kotlin/com/petqua/domain/auth/oauth/OAuthDtos.kt
  src/main/kotlin/com/petqua/domain/auth/oauth/OauthClient.kt
  src/main/kotlin/com/petqua/domain/auth/oauth/OauthServerType.kt
  src/main/kotlin/com/petqua/domain/auth/oauth/kakao/KakaoOauthApiClient.kt
  src/main/kotlin/com/petqua/domain/auth/oauth/kakao/KakaoOauthClient.kt
  src/main/kotlin/com/petqua/domain/auth/oauth/kakao/KakaoUserInfo.kt
  src/main/kotlin/com/petqua/domain/auth/token/AuthTokenProvider.kt
  src/main/kotlin/com/petqua/domain/auth/token/RefreshToken.kt
  src/main/kotlin/com/petqua/domain/auth/token/RefreshTokenRepository.kt
  src/main/kotlin/com/petqua/domain/cart/CartProductRepository.kt
  src/main/kotlin/com/petqua/domain/member/Member.kt
  src/main/kotlin/com/petqua/domain/member/MemberRepository.kt
  src/main/kotlin/com/petqua/exception/member/MemberExceptionType.kt
  src/main/kotlin/com/petqua/presentation/auth/AuthController.kt
  src/main/kotlin/com/petqua/presentation/auth/AuthExtractor.kt
  src/test/kotlin/com/petqua/application/auth/AuthFacadeServiceTest.kt
  src/test/kotlin/com/petqua/application/product/WishProductServiceTest.kt
  src/test/kotlin/com/petqua/domain/auth/AuthTokenProviderTest.kt
  src/test/kotlin/com/petqua/domain/auth/FakeKakaoOauthApiClient.kt
  src/test/kotlin/com/petqua/domain/member/MemberTest.kt
  src/test/kotlin/com/petqua/presentation/auth/AuthControllerSteps.kt
  src/test/kotlin/com/petqua/presentation/auth/AuthControllerTest.kt
  src/test/kotlin/com/petqua/test/config/OauthTestConfig.kt
  src/test/kotlin/com/petqua/test/fake/FakeKakaoOauthApiClient.kt
  src/test/kotlin/com/petqua/test/fixture/MemberFixtures.kt
Labels: feature
