Repository petqua/backend, pull requests merged in 2024-03, with the labels that each got.

#114 feature: 알림 조회 및 읽음 처리 api
  src/main/kotlin/com/petqua/application/notification/NotificationService.kt
  src/main/kotlin/com/petqua/application/notification/dto/NotificationDtos.kt
  src/main/kotlin/com/petqua/common/config/DataInitializer.kt
  src/main/kotlin/com/petqua/domain/notification/Notification.kt
  src/main/kotlin/com/petqua/domain/notification/NotificationCustomRepository.kt
  src/main/kotlin/com/petqua/domain/notification/NotificationCustomRepositoryImpl.kt
  src/main/kotlin/com/petqua/domain/notification/NotificationDynamicJpqlGenerator.kt
  src/main/kotlin/com/petqua/domain/notification/NotificationRepository.kt
  src/main/kotlin/com/petqua/exception/notification/NotificationException.kt
  src/main/kotlin/com/petqua/exception/notification/NotificationExceptionType.kt
  src/main/kotlin/com/petqua/presentation/notification/NotificationController.kt
  src/main/kotlin/com/petqua/presentation/notification/dto/NotificationDtos.kt
  src/test/kotlin/com/petqua/application/notification/NotificationServiceTest.kt
  src/test/kotlin/com/petqua/presentation/notification/NotificationControllerSteps.kt
  src/test/kotlin/com/petqua/presentation/notification/NotificationControllerTest.kt
  src/test/kotlin/com/petqua/test/fixture/NotificationFixture.kt
Labels: feature

#115 refactor: Money 값객체 생성
  src/main/kotlin/com/petqua/application/cart/CartProductService.kt
  src/main/kotlin/com/petqua/application/cart/dto/CartProductDtos.kt
  src/main/kotlin/com/petqua/application/order/OrderService.kt
  src/main/kotlin/com/petqua/application/order/dto/OrderDtos.kt
  src/main/kotlin/com/petqua/application/payment/PaymentDtos.kt
  src/main/kotlin/com/petqua/application/payment/PaymentGatewayDtos.kt
  src/main/kotlin/com/petqua/application/payment/PaymentService.kt
  src/main/kotlin/com/petqua/application/product/dto/ProductDtos.kt
  src/main/kotlin/com/petqua/common/config/DataInitializer.kt
  src/main/kotlin/com/petqua/common/config/StringToMoneyConverter.kt
  src/main/kotlin/com/petqua/common/config/WebConfig.kt
  src/main/kotlin/com/petqua/common/domain/Money.kt
  src/main/kotlin/com/petqua/domain/cart/CartProduct.kt
  src/main/kotlin/com/petqua/domain/order/Order.kt
  src/main/kotlin/com/petqua/domain/order/OrderProduct.kt
  src/main/kotlin/com/petqua/domain/payment/tosspayment/TossPayment.kt
  src/main/kotlin/com/petqua/domain/product/Product.kt
  src/main/kotlin/com/petqua/domain/product/dto/ProductDtos.kt
  src/main/kotlin/com/petqua/domain/product/option/ProductOption.kt
  src/main/kotlin/com/petqua/presentation/cart/dto/CartProductDtos.kt
  src/main/kotlin/com/petqua/presentation/order/dto/OrderDtos.kt
  src/main/kotlin/com/petqua/presentation/payment/PaymentDtos.kt
  src/main/kotlin/com/petqua/presentation/product/dto/WishProductDtos.kt
  src/test/kotlin/com/petqua/application/order/OrderServiceTest.kt
  src/test/kotlin/com/petqua/application/payment/PaymentFacadeServiceTest.kt
  src/test/kotlin/com/petqua/domain/cart/CartProductTest.kt
  src/test/kotlin/com/petqua/domain/order/OrderTest.kt
  src/test/kotlin/com/petqua/presentation/payment/PaymentControllerTest.kt
  src/test/kotlin/com/petqua/test/fake/FakeTossPaymentsApiClient.kt
  src/test/kotlin/com/petqua/test/fixture/CartProductFixtures.kt
  src/test/kotlin/com/petqua/test/fixture/OrderFixture.kt
  src/test/kotlin/com/petqua/test/fixture/PaymentFixtures.kt
  src/test/kotlin/com/petqua/test/fixture/ProductFixtures.kt
Labels: refactor

#117 fix: 봉달 상품 수정시 수량을 포함 하여 중복 검사 하도록 수정
  src/main/kotlin/com/petqua/application/cart/CartProductService.kt
  src/main/kotlin/com/petqua/application/cart/dto/CartProductDtos.kt
  src/main/kotlin/com/petqua/presentation/cart/dto/CartProductDtos.kt
  src/test/kotlin/com/petqua/application/cart/CartProductServiceTest.kt
  src/test/kotlin/com/petqua/presentation/cart/CartProductControllerTest.kt
  src/test/kotlin/com/petqua/test/fixture/CartProductFixtures.kt
Labels: fix
